name: clevertapdemo
description: A new Flutter project.
version: 0.0.1+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.0.18
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  #smooth_page_indicator: ^1.0.0+2
  smooth_page_indicator: ^1.1.0
  outline_gradient_button: ^2.0.0+1
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  flutter_masked_text2: ^0.9.1
  decimal: ^2.3.2
  intl_phone_field: ^3.1.0
  easy_localization: ^3.0.1
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.3.0
  dropdown_button2: ^1.9.2
  #stylish_bottom_bar: ^0.1.5
  stylish_bottom_bar: ^1.0.0
  syncfusion_flutter_charts: ^20.4.51
  bottom_navigation_bar: ^1.0.1
  dotted_line: ^3.1.0
  flutter_switch: ^0.3.2
  flutter_share: ^2.0.0
  expandable: ^5.0.1
  lite_rolling_switch: ^1.0.0
  carousel_indicator: ^1.0.6
  rounded_expansion_tile: ^0.0.13
  flutter_bloc: ^8.1.2
  dio: ^4.0.6
  screenshot: ^1.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  encrypt: ^5.0.1
  secure_shared_preferences: ^0.0.4
  equatable: ^2.0.5
  country_picker: ^2.0.19
  fl_country_code_picker: ^0.1.2
  form_field_validator: ^1.1.0
  syncfusion_flutter_sliders: ^20.4.51
  url_launcher: ^6.1.10
  file_picker: ^5.2.5
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  syncfusion_flutter_pdf: ^20.4.52
  chart_sparkline: ^1.0.13
  http_parser: ^4.0.2
  social_share: ^2.3.1
  password_protected_pdf_checker: ^1.0.0
  webview_flutter: ^4.0.0
  system_settings: ^2.1.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0
  google_fonts: ^3.0.1
  animate_do: ^3.0.2
  share_plus:
  path_provider: ^2.0.9
  appcheck: ^1.0.6
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  app_settings: ^5.0.0

  percent_indicator: ^4.2.3
  razorpay_flutter_customui: ^1.3.3
  #razorpay_flutter: ^1.3.4
  scrollable_list_tab_scroller: ^1.1.0
  clevertap_plugin: ^1.6.0
  flutter_screenutil: ^5.7.0
  table_calendar: ^3.0.8
  month_year_picker: ^0.2.0+3
  flutter_localization: ^0.1.10
  scrollable_positioned_list: ^0.3.5
  flutter_overlay_loader: ^2.0.0
  flutter_slidable: ^3.0.0
  marqueer: ^1.4.0
  flutter_widget_from_html:
  phone_selector: ^3.0.0
  local_auth: ^2.1.6
  circular_countdown_timer: ^0.2.3
  flutter_countdown_timer: ^4.1.0
  coloredcontainer:
    git:
      url: git@github.com:shri-rang/kycpackage.git
      ref: feature_dev_local
  flutter_launcher_icons: ^0.13.1
  marquee_widget: ^1.2.0
  uni_links: ^0.5.1
  change_app_package_name: ^1.1.0
  # marqueer: ^1.4.0
  firebase_crashlytics: ^3.3.1
  appsflyer_sdk:
  firebase_remote_config:
  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.3
  firebase_dynamic_links: ^5.3.3
  external_app_launcher: ^3.1.0
  package_info_plus: ^4.0.2
  http: ^0.13.6
  flutter_image_compress: ^2.0.3
  firebase_messaging: ^14.4.0

  # coloredcontainer:
  #   git:
  #     url: git@github.com:shri-rang/kycpackage.git
  #     ref: feature_dev_local

  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_image23.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/www/
    - assets/gif/lpage/
    - assets/images/landingpage/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoBlack.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
